stages:
    - testing
    - deploy

test:
  stage: testing
  image: php:7.3
  script:
    # this is a quick syntactic check for php files
    - php --version
    - ./check_php_syntax.sh
    # TODO phpunit unit tests, phpunit db tests

deploy_prod:
    stage: deploy
    image: ruby:2
    only:
        - master
    environment:
        name: production
        url: https://$HEROKU_APP_NAME.herokuapp.com/
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
