stages:
    - testing
    - deploy

test:
  stage: testing
  image: composer:1.10
  variables:
    POSTGRES_USER: "app"
    POSTGRES_PASSWORD: "unsafe-password"
    # the next variable is used by the psql client to run the schema.sql script
    PGPASSWORD: "$POSTGRES_PASSWORD"
    DATABASE_URL: "psql://app:unsafe-password@db:5432/app"
  services:
    - name: postgres:12.2
      alias: db
  script:
    # install postgres driver
    - apk add postgresql-dev postgresql-client
    - "docker-php-ext-install pdo_pgsql > /dev/null"
    # output info, so we know what we're running on...
    - php --version
    - composer --version
    # this is a quick syntactic check for php files
    - ./check_php_syntax.sh
    - composer install --quiet
    - composer check-platform-reqs
    # unit tests (no database access)
    - ./vendor/bin/phpunit --testdox --bootstrap ./vendor/autoload.php --no-configuration ./tests/unit
    # database tests
    - psql -q -f ./db/schema.sql -h db -p 5432 -U app app
    - ./vendor/bin/phpunit --testdox --bootstrap ./vendor/autoload.php --no-configuration ./tests/db

deploy_prod:
    stage: deploy
    image: ruby:2
    only:
        - master
    environment:
        name: production
        url: https://$HEROKU_APP_NAME.herokuapp.com/
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
